### ISSUE TITLE
Backend crashes without frontend/build/static directory in place

### ISSUE THREAD

**Issue by ItsEcholot** [ItsEcholot/real-stereo-extended#11]
The backend fails to start without the `frontend/build/static` directory in place. I'm not sure if this should be classified as a bug but it gets in the way when developing and thus using `create-react-app` scripts for serving.

```python
No directory exists at '/workspaces/real-stereo-extended/frontend/build/static'
  File "/workspaces/real-stereo-extended/backend/src/api/manager.py", line 36, in __init__
    self.app.add_routes([
  File "/workspaces/real-stereo-extended/backend/src/__main__.py", line 10, in <module>
    api = ApiManager('master', tracking)
```

**Comment by cyrilwanner** [comment]
Yeah, that's a bug, looks like the new library used for the webserver handles static routes differently than the one used previously. I'll add a check for that 👍
