### ISSUE TITLE
Allow user to select balancing volume

### ISSUE THREAD

**Issue by ItsEcholot** [ItsEcholot/real-stereo-extended#57]
As mentioned in #53, we should allow the user to change the volume at which the audio balancing should take place. Either through the webapp, or by listening to volume change events emitted by the Sonos group coordinator (this way native volume controls could be possible, but how can we differentiate from our own volume change events from balancing?).

**Comment by cyrilwanner** [comment]
I would prefer it if we can listen to native volume events. Having to change it in our webapp would be a bit strange as the controls implemented in the Sonos app, spotify, etc. wouldn't work.

I was thinking that we can compare the volume in the change events with the ones we last sent to sonos. If they don't match, the user (or another source) changed them and we can adjust our target volume. I'll try this today and report back in case it doesn't work.

**Comment by ItsEcholot** [comment]
I agree that listening to the volume change events would be preferable 👍 It should be possible using http://docs.python-soco.com/en/v0.22.0/api/soco.events.html#module-soco.events_asyncio... But I haven't looked much into it yet
