### ISSUE TITLE
Calibration sound playing on both speakers at the same time

### ISSUE THREAD

**Issue by cyrilwanner** [ItsEcholot/real-stereo-extended#80]
The first position works correctly but when coming to the second position, the following problem occurs.

The noise on the first speaker is only played for a few milliseconds, after that, it is completely silent. Because of this, the recorded volume for speaker 1 is 0%. When it tries to play it on the second speaker after some seconds, it gets played on both speakers at the same time.

The speakers are configured as a stereo pair.

**Comment by ItsEcholot** [comment]
Haven't stumbled upon this one yet... Will investigate tomorrow 👍
