### ISSUE TITLE
Interpolation preview during calibration is red

### ISSUE THREAD

**Issue by cyrilwanner** [ItsEcholot/real-stereo-extended#81]
The interpolation preview during calibration has a red background, making it really hard to see the cross of your own position.

In the code, I see that it should somehow be random, but it was now red in 4 consecutive calibrations and for both speakers.

**Comment by ItsEcholot** [comment]
The color isn't really random but selected using the index passed into the function (like a seed). This is used to display the interpolation for the different speakers. Index 1 is red. I agree this isn't the best, I will change the color 👍
